apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: helm-guestbook
    valuesFile: https://raw.githubusercontent.com/vnaboichenko/argocd-example-apps/master/helm-guestbook/dynamic-values-vladn.yaml
#    valuesInline:
#      meraki:
#        region: use
#      prefix: test-
