apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../

helmCharts:
  - name: helm-guestbook
    valuesFile: http://metrics-api-lb.shard-proxy.use.development.k8s.ikarem.io:8000/helm/sandbox.meraki.com/meraki_random_values
#    valuesInline:
#      meraki:
#        region: use
#      prefix: test-
